default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: bills_agent_dev

test:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: bills_agent_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>